-- A El teléfono y el correo de los directores, vendedores y clientes son obligatorios y no se pueden compartir entre ellos. Es decir, son campos UNICOS.

ALTER TABLE DIRECTOR ADD CONSTRAINT U_TEL_DIR UNIQUE(TELEFONO);

ALTER TABLE VENDEDOR ADD CONSTRAINT U_TEL_VEND UNIQUE(TELEFONO);

ALTER TABLE CLIENTE ADD CONSTRAINT U_TEL_CL UNIQUE(TELEFONO);

-- B El campo Telefono de las tablas Director, Vendedor y Cliente debe tener nueve dígitos.

ALTER TABLE DIRECTOR MODIFY TELEFONO NUMBER(9) NOT NULL;
ALTER TABLE DIRECTOR ADD CONSTRAINT CK_NUMERO_DIR CHECK (LENGTH(TELEFONO)=9);

ALTER TABLE VENDEDOR MODIFY TELEFONO NUMBER(9) NOT NULL;
ALTER TABLE VENDEDOR ADD CONSTRAINT CK_NUMERO_VEND CHECK (LENGTH(TELEFONO)=9);

ALTER TABLE CLIENTE MODIFY TELEFONO NUMBER(9) NOT NULL;
ALTER TABLE CLIENTE ADD CONSTRAINT CK_NUMERO_CL CHECK (LENGTH(TELEFONO)=9);

-- C En la tabla Venta el DNI del vendedor debe ser distinto al DNI del cliente.

ALTER TABLE VENTA ADD CONSTRAINT CK_DNI_VENDCL CHECK (DNI_VENDEDOR <> DNI_CLIENTE);

-- D En la tabla Producto la descripción es único y para las claves foráneas Familia y Genero se incluye la restricción de integridad referencial ON DELETE SET NULL.

ALTER TABLE PRODUCTO ADD CONSTRAINT U_DESC_PROD UNIQUE(DESCRIPCION);

ALTER TABLE PRODUCTO MODIFY FK_FAMILIA ON DELETE SET NULL;

ALTER TABLE PRODUCTO MODIFY FK_GENERO ON DELETE SET NULL;

-- E

ALTER TABLE LINEAVENTA ADD CONSTRAINT CK_NUMLINEA CHECK NUMLINEA BETWEEN 1 AND 99;


