CREATE TABLE FABRICANTE(
CODFAB NUMBER(2) NOT NULL,
FABRICANTE VARCHAR(3) NOT NULL,
CONSTRAINT PK_FABRICANTE PRIMARY KEY (CODFAB)
);

CREATE TABLE MARCA(
CODMARCA NUMBER(2) NOT NULL,
MARCA VARCHAR(30) NOT NULL,
CONSTRAINT PK_MARCA PRIMARY KEY (CODMARCA)
)

CREATE TABLE VEHICULO(
CODVEH VARCHAR(7) NOT NULL,
MODELO VARCHAR(30) NOT NULL,
TIPO VARCHAR(10) NOT NULL,
COLOR VARCHAR(30) NOT NULL,
CODFAB_FABRICANTE NUMBER(2) NOT NULL,
CODMARCA_MARCA NUMBER(2) NOT NULL,
CONSTRAINT PK_VEHICULO PRIMARY KEY (CODVEH),
CONSTRAINT FK_CODFAB_FABRICANTE FOREIGN KEY (CODFAB_FABRICANTE) REFERENCES FABRICANTE(CODFAB),
CONSTRAINT FK_CODMARCA_MARCA FOREIGN KEY (CODMARCA_MARCA) REFERENCES MARCA(CODMARCA)
);

CREATE TABLE CLIENTE(
DNI VARCHAR(9) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
PRAPELLIDO VARCHAR (50) NOT NULL,
SGAPELLIDO VARCHAR(50) NULL,
DOMICILIO VARCHAR(50) NOT NULL,
NUMTARJETA NUMBER(20) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);

CREATE TABLE EMPLEADO(
DNI VARCHAR(9) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
PRAPELLIDO VARCHAR (50) NOT NULL,
SGAPELLIDO VARCHAR(50) NULL,
DOMICILIO VARCHAR(50) NOT NULL,
NUMCUENTA NUMBER(20) NOT NULL,
CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI)
);

CREATE TABLE ALQUILER(
CODALQUILER NUMBER(3) NOT NULL,
FECHA DATE NOT NULL,
NUMDIAS NUMBER(2) NOT NULL,
KMACTUAL NUMBER(7) NOT NULL,
KMENTREGA NUMBER(7) NOT NULL,
DNI_CLIENTE VARCHAR (9) NULL,
CODVEH VARCHAR(7) NULL,
DNI_EMPLEADO VARCHAR(9) NOT NULL,
CONSTRAINT PK_ALQUILER PRIMARY KEY (CODALQUILER),
CONSTRAINT FK_DNI_CLIENTE_CLIENTE FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI),
CONSTRAINT FK_DNI_EMPLEADO_EMPLEADO FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI)
);

CREATE TABLE OFICINA(
CODOFICINA NUMBER(3) NOT NULL,
DOMICILIO VARCHAR(50) NOT NULL,
TELEFONO NUMBER(9) NOT NULL,
CONSTRAINT FK_OFICINA PRIMARY KEY (CODOFICINA)
);

CREATE TABLE OFICINASALQ(
CODALQUILER NUMBER(3) NOT NULL,
CODOFICINA NUMBER (3) NOT NULL,
CONSTRAINT PK_OFICINASALQ PRIMARY KEY (CODALQUILER,CODOFICINA),
CONSTRAINT CODALQUILER_ALQUILER FOREIGN KEY (CODALQUILER) REFERENCES ALQUILER(CODALQUILER),
CONSTRAINT CODOFICINA_OFICINA FOREIGN KEY (CODOFICINA) REFERENCES OFICINA(CODOFICINA)
);

CREATE TABLE CURSO(
CODCURSO NUMBER (3) NOT NULL,
DESCRIPCION VARCHAR(300) NOT NULL,
NUMHORAS NUMBER (4) NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PK_CURSO PRIMARY KEY (CODCURSO)
);

CREATE TABLE CURSOEMPL(
CODCURSO NUMBER (3) NOT NULL,
DNI_EMPLEADO VARCHAR(9) NOT NULL,
CONSTRAINT PK_CURSOEMPL PRIMARY KEY (CODCURSO,DNI_EMPLEADO),
CONSTRAINT FK_CODCURSO_CURSO FOREIGN KEY (CODCURSO) REFERENCES CURSO(CODCURSO),
CONSTRAINT FK_DNI_EMPLEADO FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI)
);
