--4.13

--Consulta el nombre de los profesores que hablan idioma Español
SELECT NOMBRE FROM DATOSPERSONALES,PROFESOR,IDIOMASPROF,IDIOMA WHERE TIPO ='PROFESOR' AND DATOSPERSONALES.DNI = PROFESOR.DNI AND PROFESOR.DNI = IDIOMASPROF.DNI_PROFESOR AND IDIOMASPROF.CODIDIOMA_IDIOMA = IDIOMA.CODIDIOMA AND IDIOMA.DESCRIPCION = 'Español';
--Consulta las asignaturas que pertenecen al ciclo de DAM
SELECT ASIGNATURA.NOMBRE FROM ASIGNATURA,CICLOFORM WHERE CICLOFORM.NOMBRE = 'DAM' AND CICLOFORM.CODCICLO = ASIGNATURA.CODCICLO_CICLOFORM;
--Consulta el nombre y el número de cuenta asociado a cada profesor.
SELECT DATOSPERSONALES.NOMBRE,PROFESOR.CUENTA FROM DATOSPERSONALES,PROFESOR WHERE DATOSPERSONALES.TIPO = 'PROFESOR' AND PROFESOR.DNI = DATOSPERSONALES.DNI;
--Filtra los alumnos que estén registrados en la tabla DatosPersonales
SELECT * FROM DATOSPERSONALES WHERE DATOSPERSONALES.TIPO = 'ALUMNO';
--Filtra los profesores que estén registrados en la tabla DatosPersonales
SELECT * FROM DATOSPERSONALES WHERE DATOSPERSONALES.TIPO = 'PROFESOR';
--Consulta el email y el nombre de todos los alumnos.
SELECT ALUMNO.EMAIL,DATOSPERSONALES.NOMBRE FROM ALUMNO,DATOSPERSONALES WHERE DATOSPERSONALES.TIPO = 'ALUMNO' AND DATOSPERSONALES.DNI = ALUMNO.DNI;
--Consulta el email y el nombre de los alumnos matriculados en Empresa.
SELECT ALUMNO.EMAIL,DATOSPERSONALES.NOMBRE FROM ALUMNO,DATOSPERSONALES,ASIGNATURA,MATRICULA WHERE DATOSPERSONALES.TIPO = 'ALUMNO' AND DATOSPERSONALES.DNI = ALUMNO.DNI AND ALUMNO.DNI = MATRICULA.DNI_ALUMNO AND MATRICULA.CODASIG_ASIGNATURA = ASIGNATURA.CODASIG AND ASIGNATURA.NOMBRE = 'Empresa';
--Consulta el nombre del módulo al que pertenecen los alumnos (se debe visualizar el nombre del alumno y el nombre del módulo).
SELECT DATOSPERSONALES.NOMBRE NOMBREALUMNO,CICLOFORM.NOMBRE NOMBRECICLO FROM DATOSPERSONALES,CICLOFORM,MATRICULA,ASIGNATURA WHERE DATOSPERSONALES.TIPO = 'ALUMNO' AND DATOSPERSONALES.DNI = MATRICULA.DNI_ALUMNO AND MATRICULA.CODASIG_ASIGNATURA = ASIGNATURA.CODASIG AND ASIGNATURA.CODCICLO_CICLOFORM = CICLOFORM.CODCICLO;
--Consulta el nombre de las asignaturas de las que está matriculado Pedro.
SELECT ASIGNATURA.NOMBRE FROM ASIGNATURA,MATRICULA,DATOSPERSONALES WHERE DATOSPERSONALES.NOMBRE = 'PEDRO' AND DATOSPERSONALES.DNI = MATRICULA.DNI_ALUMNO AND MATRICULA.CODASIG_ASIGNATURA = ASIGNATURA.CODASIG;
--Consulta los grados que son de tipo GRADO SUPERIOR
SELECT CICLOFORM.NOMBRE FROM CICLOFORM WHERE TIPO = 'GRADO SUPERIOR';
--Consulta qué asignaturas son de cada ciclo. (usando alias)
SELECT CICLOFORM.NOMBRE NOMBRECICLO,ASIGNATURA.NOMBRE NOMBREASIG FROM CICLOFORM,ASIGNATURA WHERE CICLOFORM.CODCICLO = ASIGNATURA.CODCICLO_CICLOFORM;
--Consulta las asignaturas que tengan un numero de horas menor que 200
SELECT ASIGNATURA.NOMBRE FROM ASIGNATURA WHERE ASIGNATURA.NUMHORAS < 200;

--Actualiza el apellido 2 al nombre de Andrea dejándolo nulo.
SELECT * FROM DATOSPERSONALES WHERE DATOSPERSONALES.NOMBRE = 'ANDREA';
UPDATE DATOSPERSONALES SET DATOSPERSONALES.APELLIDO2 = NULL WHERE DATOSPERSONALES.NOMBRE = 'ANDREA';
--Eliminar las matrículas de los alumnos que tengan la asignatura de Programación
SELECT MATRICULA.* FROM MATRICULA,ASIGNATURA WHERE MATRICULA.CODASIG_ASIGNATURA = ASIGNATURA.CODASIG AND ASIGNATURA.NOMBRE = 'Programación';
DELETE MATRICULA WHERE MATRICULA.CODASIG_ASIGNATURA = '5';
--Se elimina la asignatura de Empresa y todas las matrículas de los alumnos.
SELECT MATRICULA.* FROM MATRICULA,ASIGNATURA WHERE MATRICULA.CODASIG_ASIGNATURA = ASIGNATURA.CODASIG AND ASIGNATURA.NOMBRE = 'Empresa';
DELETE MATRICULA WHERE MATRICULA.CODASIG_ASIGNATURA = '1';
SELECT ASIGNATURA.* FROM ASIGNATURA WHERE ASIGNATURA.NOMBRE = 'Empresa';
DELETE ASIGNATURA WHERE ASIGNATURA.CODASIG = '1';
--Actualiza del nombre de la asignatura Bases de datos para poner BBDD.
SELECT * FROM ASIGNATURA WHERE ASIGNATURA.NOMBRE = 'Bases de datos';
UPDATE ASIGNATURA SET ASIGNATURA.NOMBRE = 'BBDD' WHERE ASIGNATURA.NOMBRE = 'Bases de datos';
--Incluye un nuevo registro en CICLOFORM para añadir un nuevo grado medio con código 6365, nombre ELEC.
INSERT INTO CICLOFORM(CODCICLO,NOMBRE,TIPO) VALUES (6365,'ELEC','GRADO MEDIO');
--Incluye una nueva asignatura en la tabla Asignatura, perteneciente al ciclo ELEC, llamada “Circuitos Baja Potencia” y número de horas 100. La imparte el mismo profesor que la asignatura de Aplicaciones Web.
INSERT INTO ASIGNATURA(CODASIG,NOMBRE,NUMHORAS,DNI_PROFESOR,CODCICLO_CICLOFORM) VALUES('6','Circuitos Baja Potencia',100,'89621477A',6365);
--Pedro cambia la matrícula de Informática Industrial por la de Aplicaciones Web. Actualiza las tablas correspondientes.
SELECT MATRICULA.* FROM MATRICULA,DATOSPERSONALES WHERE DATOSPERSONALES.NOMBRE = 'PEDRO' AND DATOSPERSONALES.DNI = MATRICULA.DNI_ALUMNO;
UPDATE MATRICULA SET MATRICULA.CODASIG_ASIGNATURA = '3' WHERE MATRICULA.DNI_ALUMNO = '11526987G';
--Se añade un nuevo idioma, alemán, cuyo código es 50 ya que el profesor Jesús habla este idioma. Actualiza las tablas correspondientes
INSERT INTO IDIOMA(CODIDIOMA,DESCRIPCION) VALUES('50','Alemán');
INSERT INTO IDIOMASPROF(CODIDIOMA_IDIOMA,DNI_PROFESOR) VALUES('50','44103779F');